namespace Altalents.DataAccess.EntityConfigurations
{
    internal class TexteDiversEntityConfiguration : IEntityTypeConfiguration<TexteDivers>
    {
        public void Configure(EntityTypeBuilder<TexteDivers> builder)
        {
            EntityTypeBuilderBaseHelper<TexteDivers>.ConfigureBase(builder);
            builder.ToTable("TexteDivers");

            builder.Property(e => e.TitreFr)
                .HasMaxLength(250);

            builder.Property(e => e.TitreEn)
                .HasMaxLength(250);

            builder.Property(e => e.Type)
                .HasColumnType("varchar")
                .HasMaxLength(100);

            builder.HasIndex(e => new { e.Type });
            builder.HasIndex(e => new { e.TitreFr });
            builder.HasIndex(e => new { e.TitreEn });

            builder.HasData(new List<TexteDivers> {
                new TexteDivers(){
                    Id = Guid.Parse("8B9901EC-A96E-4AF0-84DB-52A2A5C7362D"),
                    DateCrea = new DateTime(2023, 5, 16),
                    UtiCrea= "ALTEA",
                    TitreFr = "Crédits et mentions légales",
                    TitreEn = "Credits and legal notices",
                    DetailFr = "<p>\r\n\tConception et architecture de la base de donn&eacute;es : copyright Jean <span data-scayt_word=\"Nicollier\" data-scaytid=\"1\">Nicollier</span>.<br />\r\n\tL&rsquo;interface a &eacute;t&eacute; r&eacute;alis&eacute;e par <a href=\"http://www.loodvrij.nl\"><span data-scayt_word=\"Loodvrij\" data-scaytid=\"2\">Loodvrij</span></a> : <span data-scayt_word=\"Heleen\" data-scaytid=\"3\">Heleen</span> <span data-scayt_word=\"Lamers\" data-scaytid=\"4\">Lamers</span> (pour la maquette) et <span data-scayt_word=\"Martin\" data-scaytid=\"5\">Martin</span> <span data-scayt_word=\"Timmers\" data-scaytid=\"6\">Timmers</span> (pour la programmation).<br />\r\n\t<br />\r\n\tR&eacute;dacteurs : <span data-scayt_word=\"Rhea\" data-scaytid=\"7\">Rhea</span> <span data-scayt_word=\"Sylvia\" data-scaytid=\"8\">Sylvia</span> <span data-scayt_word=\"Blok\" data-scaytid=\"9\">Blok</span>, <span data-scayt_word=\"Peter\" data-scaytid=\"10\">Peter</span> <span data-scayt_word=\"Fuhring\" data-scaytid=\"11\">Fuhring</span>, <span data-scayt_word=\"Valérie\" data-scaytid=\"12\">Val&eacute;rie</span> <span data-scayt_word=\"Lavergne-Durey\" data-scaytid=\"13\">Lavergne-Durey</span>, <span data-scayt_word=\"Laurence\" data-scaytid=\"14\">Laurence</span> <span data-scayt_word=\"Lhinares\" data-scaytid=\"15\">Lhinares</span>.<br />\r\n\tCoordination &eacute;ditoriale : Claire <span data-scayt_word=\"Lagarde\" data-scaytid=\"16\">Lagarde</span>.<br />\r\n\tDocumentaliste : Marie-Claire <span data-scayt_word=\"Nathan\" data-scaytid=\"17\">Nathan</span>.</p>\r\n<p>\r\n\tLa mise &agrave; jour de la base est assur&eacute;e continuellement, une date d&rsquo;&eacute;dition s&rsquo;inscrit automatiquement lors de l&rsquo;impression des fiches.</p>\r\n<p>\r\n\tAttention, le contenu de cette base ne refl&egrave;te pas n&eacute;cessairement le dernier &eacute;tat du savoir.</p>\r\n<p>\r\n\tCiter la base : Frits <span data-scayt_word=\"Lugt\" data-scaytid=\"19\">Lugt</span>, <i>Les marques de collections de dessins &amp; d&rsquo;estampes</i>, &eacute;dition en ligne par la <a href=\"http://www.fondationAltalents.fr\">Fondation <span data-scayt_word=\"Altalents\" data-scaytid=\"20\">Altalents</span></a>, date de consultation.<br />\r\n\t<br />\r\n\t<a href=\"http://www.marquesdecollections.fr\"><span data-scayt_word=\"http\" data-scaytid=\"22\">http</span>://<span data-scayt_word=\"www.marquesdecollections.fr\" data-scaytid=\"18\">www.marquesdecollections.fr</span>.</a><br />\r\n\t<br />\r\n\t&copy; Fondation <span data-scayt_word=\"Altalents\" data-scaytid=\"26\">Altalents</span>/ Mus&eacute;e du <span data-scayt_word=\"Louvre\" data-scaytid=\"34\">Louvre</span> 2011. Tous droits r&eacute;serv&eacute;s sur tous les renseignements sur ce site.<br />\r\n\t&nbsp;</p>",
                    DetailEn = "<p>\r\n\tDatabase concept: copyright &copy; Jean Nicollier (Elseneur). The interface was created by <a href=\"http://www.loodvrij.nl\">Loodvrij</a>, with Heleen Lamers in charge of the layout and Martin Timmers, the programming.<br />\r\n\t<br />\r\n\tWriters: Rhea Sylvia Blok, Peter Fuhring, Val&eacute;rie Lavergne-Durey, Laurence Lhinares.<br />\r\n\tEditorial coordination: Claire Lagarde.<br />\r\n\tDocumentalist: Marie-Claire Nathan.<br />\r\n\t<br />\r\n\tThe database is constantly updated; the date of edition is automatically displayed when the records are printed.<br />\r\n\t<br />\r\n\tPlease note that the content of this database does not necessarily reflect the most up-to-date state of knowledge in the domain.<br />\r\n\t<br />\r\n\tTo quote from the database: Frits Lugt, <em>Les Marques de collections de dessins &amp; d&rsquo;estampes</em>, online edition by the <a href=\"http://fondationAltalents.fr\">Fondation Altalents</a>, consultation date.<br />\r\n\t<br />\r\n\t<a href=\"http://www.marquesdecollections.fr\">http://www.marquesdecollections.fr</a>.<br />\r\n\t<br />\r\n\t&copy; Fondation Altalents/ Mus&eacute;e du Louvre 2011. All rights reserved with regard to all information on this web site.</p>",
                    Type = EnumTypeTexteDivers.CreditsEtMentionsLegales
                },
                new TexteDivers(){
                    Id = Guid.Parse("7404FBAC-04E9-4A98-B94F-4E659D8F015F"),
                    DateCrea = new DateTime(2023, 5, 29),
                    UtiCrea= "ALTEA",
                    TitreFr = "Contact",
                    TitreEn = "Contact",
                    DetailFr = "<p><em>Signaler une marque de collection sur un dessin ou une estampe</em><br> </p>\r\n<p>Pour signaler une marque, veuillez nous envoyer par mail sa description et une photo numérique au format jpeg, de préférence avec une règle (en mm) à côté de la marque. <br> <br> Veuillez également joindre les informations suivantes&nbsp;:</p>\r\n<p>– technique de la marque (manuscrite ou estampée, couleur, dimensions)<br> – localisation de la marque (recto, verso, montage)<br> – sur quelle œuvre (ou œuvres) la marque est apposée. Si l’œuvre est conservée dans une collection publique, merci de le préciser en ajoutant le numéro d’inventaire<br> – toute autre information utile (biographie du collectionneur, caractéristique, origine et formation de la collection, etc…)&nbsp; <br> <br> Veuillez indiquer vos propres coordonnées (nom et adresse e-mail) pour que nous puissions vous contacter.</p>\r\n<p><br> <em>Coordonnées</em> <br> <br> Fondation Altalents | Collection Frits Lugt<br> 121, Rue de Lille<br> 75007 Paris<br> Tél.&nbsp;: +33 (0)1 47 05 75 19<br> Email&nbsp;: <a href=\"mailto:marques@fondationAltalents.fr\">marques@fondationAltalents.fr</a><br> <br> </p>\r\n<p><br> <br> Les informations recueillies sont destinées au département de recherche sur les marques de collections à \r\nla Fondation Altalents et seront traitées afin d’améliorer les connaissances sur les marques de collection dans le but d’actualiser \r\nla base de données <em>Les Marques de collections de dessins &amp; d’estampes</em>. Elles sont traitées avec la plus stricte confidentialité.<br> <br> Conformément à la loi «&nbsp;Informatique et Libertés&nbsp;» du 6 janvier 1978 modifiée par la loi du 6 août 2004, vous disposez sur vos données d’un droit d’accès, de rectification, de limitation, de portabilité et de suppression. Pour exercer ces droits, vous pouvez contacter la Fondation Altalents, 121 rue de Lille, 75007 Paris, +33 (0)1 47 05 75 19, <a href=\"mailto:coll.lugt@fondationAltalents.fr\">coll.lugt@fondationAltalents.fr</a>.<br> <br></p>",
                    DetailEn = "<p><em>Submit a collector’s mark on a drawing or a print</em><br> <br> To submit information about a mark please e-mail us its description, joining a digital photograph of the mark in jpeg, preferably with a ruler (in mm) by its side.<br> <br> Please also include the following information:<br> <br> – technique of the mark (handwritten or stamped, colour, size)<br> – location of the mark (recto, verso, mount)<br> – on what work of art (or works) the mark is used. If the work is in a public collection, please specify and include an inventory number<br> – all other useful information (biography of the collector, characteristics, origin and history of the collection, etc.)<br> <br> Finally, please include your contact details (name and e-mail address) so that we can get in touch with you.<br> <br> <br> <em>Contact details</em> <br> <br> Fondation Altalents | Collection Frits Lugt<br> 121, Rue de Lille<br> 75007 Paris<br> Tel: +33 (0)1 47 05 75 19<br> Email: <a href=\"mailto:marques@fondationAltalents.fr\">marques@fondationAltalents.fr</a></p>\r\n<p>&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p><br> The information supplied is collected by the collectors’ marks research department at the Fondation Altalents and is used for research on collectors’ marks in order to update the database <em>Les Marques de collections de dessins &amp; d’estampes</em>. The data will not be used for other purposes and will be treated with confidentiality.<br> <br> In accordance with the provisions of law no. 78-17 on computers, files and privacy of 6 January 1978, amended by law no. 2004-801 of 6 August 2004, you are entitled to access, correct, restrict or suppress your personal data. If you wish to exercise these rights, you can contact the Fondation Altalents, 121 rue de Lille, 75007 Paris, France, +33 (0)1 47 05 75 19, <a href=\"mailto:coll.lugt@fondationAltalents.fr\">coll.lugt@fondationAltalents.fr</a>.<br> <br>\r\n</p><p>&nbsp;</p>",
                    Type = EnumTypeTexteDivers.Contact
                }
            });
        }
    }
}
