//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altalents.Commun.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessExceptionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessExceptionsResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Altalents.Commun.Resources.BusinessExceptionsResources", typeof(BusinessExceptionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business Error.
        /// </summary>
        public static string BUSINESS_EXCEPTION {
            get {
                return ResourceManager.GetString("BUSINESS_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet élément n&apos;est pas modifiable..
        /// </summary>
        public static string ELEMENT_NON_MODIFIABLE {
            get {
                return ResourceManager.GetString("ELEMENT_NON_MODIFIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une image est obligatoire..
        /// </summary>
        public static string IMAGE_OBLIGATOIRE {
            get {
                return ResourceManager.GetString("IMAGE_OBLIGATOIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet onglet existe déjà pour cette marque..
        /// </summary>
        public static string LIBELLE_ONGLET_NOTICE_MARQUE_EXIST {
            get {
                return ResourceManager.GetString("LIBELLE_ONGLET_NOTICE_MARQUE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le titre est obligatoire..
        /// </summary>
        public static string LIBELLE_ONGLET_NOTICE_MARQUE_REQUIRED {
            get {
                return ResourceManager.GetString("LIBELLE_ONGLET_NOTICE_MARQUE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum d&apos;image déjà atteint.
        /// </summary>
        public static string MAXIMUM_IMAGE_ATTEINT {
            get {
                return ResourceManager.GetString("MAXIMUM_IMAGE_ATTEINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mots de passe différents..
        /// </summary>
        public static string MDP_DIFFERENTS {
            get {
                return ResourceManager.GetString("MDP_DIFFERENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom principal est obligatoire..
        /// </summary>
        public static string NOM_PRINCIPAL_OBLIGATOIRE {
            get {
                return ResourceManager.GetString("NOM_PRINCIPAL_OBLIGATOIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au moins une notice doit être publiée..
        /// </summary>
        public static string NOTICE_NON_PUBLIEE {
            get {
                return ResourceManager.GetString("NOTICE_NON_PUBLIEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;ordre d&apos;apparition est obligatoire et supérieur ou égal à 1..
        /// </summary>
        public static string ORDRE_APPARITION_REQUIRED {
            get {
                return ResourceManager.GetString("ORDRE_APPARITION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les champs ordre français et ordre anglais sont obligatoires et doivent être supérieurs ou égaux à 1..
        /// </summary>
        public static string ORDRES_INTRODUCTION_REQUIRED {
            get {
                return ResourceManager.GetString("ORDRES_INTRODUCTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce mot-clé est inconnu..
        /// </summary>
        public static string REFERENCE_INCONNUE {
            get {
                return ResourceManager.GetString("REFERENCE_INCONNUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce mot-clé ne peut pas être supprimé car il est rattaché à un autre mot-clé ou à une marque..
        /// </summary>
        public static string REFERENCE_NON_SUPPRIMABLE {
            get {
                return ResourceManager.GetString("REFERENCE_NON_SUPPRIMABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le texte est obligatoire..
        /// </summary>
        public static string TEXTE_MARQUE_REFERENCE_LIBRE_REQUIRED {
            get {
                return ResourceManager.GetString("TEXTE_MARQUE_REFERENCE_LIBRE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les textes des notices sont obligatoires..
        /// </summary>
        public static string TEXTE_NOTICE_REQUIRED {
            get {
                return ResourceManager.GetString("TEXTE_NOTICE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les champs titre français et titre anglais sont obligatoires..
        /// </summary>
        public static string TITRES_INTRODUCTION_REQUIRED {
            get {
                return ResourceManager.GetString("TITRES_INTRODUCTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce type de mot-clé est inconnu..
        /// </summary>
        public static string TYPE_REFERENCE_INCONNU {
            get {
                return ResourceManager.GetString("TYPE_REFERENCE_INCONNU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet utilisateur est en lecture seule. Aucune modification possible..
        /// </summary>
        public static string UTILISATEUR_LECTURE_SEULE {
            get {
                return ResourceManager.GetString("UTILISATEUR_LECTURE_SEULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet utilisateur n&apos;est pas modifiable..
        /// </summary>
        public static string UTILISATEUR_NON_MODIFIABLE {
            get {
                return ResourceManager.GetString("UTILISATEUR_NON_MODIFIABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cet utilisateur n&apos;est pas supprimable..
        /// </summary>
        public static string UTILISATEUR_NON_SUPPRIMABLE {
            get {
                return ResourceManager.GetString("UTILISATEUR_NON_SUPPRIMABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de supprimer l&apos;utilisateur connecté..
        /// </summary>
        public static string UTILISATEUR_NON_SUPPRIMABLE_CONNECTE {
            get {
                return ResourceManager.GetString("UTILISATEUR_NON_SUPPRIMABLE_CONNECTE", resourceCulture);
            }
        }
    }
}
