// <auto-generated />
using System;
using Altalents.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Altalents.DataAccess.Migrations
{
    [DbContext(typeof(MigrationContext))]
    [Migration("20240617150900_AddLangues")]
    partial class AddLangues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Altalents.Entities.Reference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("SousType")
                        .HasMaxLength(250)
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasMaxLength(250)
                        .HasColumnType("int");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "SousType");

                    b.ToTable("References", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc2fe62f-a81d-437b-a257-7e89b150042e"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Anglais",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("2ad460a4-afa9-4ac0-986f-42d626b82bf1"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Arabe",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("e47e9d1a-590d-4b4a-8f9e-219781d36902"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Chinois",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("91cad6f6-cfb2-43bc-b5f5-a1e90ceba77c"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Espagnol",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("356fce26-caaa-4b4e-94d2-f7341d1851b1"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Français",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("3fbcdd3e-7dfa-46bb-bf5d-ae39e4137a07"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Russe",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("cfb960f2-d501-4154-a53a-83f9497bc0ad"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Albanais",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("fe2be6bb-fbda-4115-bc06-5603447cbcbd"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Allemand",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("9a5769e9-f63f-4f30-85d6-c785247a621a"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Amazigh",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("3ca6db24-303d-4fa3-9b5b-5cd8cfd02f11"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Arménien",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("8883e43d-9d64-4976-a0de-cf2fce12c00d"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Aymara",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("f3e4d4b8-4406-4098-ae7f-1ccbf938c5b8"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Bengali",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("389314c5-b5b2-4055-85ef-a0a688b71d1c"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Catalan",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("560f923c-27de-4891-8e96-db9fe47ca235"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Coréen",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("077fa7cc-9f80-4d11-a791-1109ec17987b"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Croate",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("eb36539d-64bd-4cd7-adc9-27fe1c30a039"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Danois",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("41fb2299-36ec-4854-bc78-ee7899af318f"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Éwé",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("57580b70-c631-4d9c-8dfa-920b54bfbfaf"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Guarani",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("1fbfbf6e-957e-4565-afd1-173b5cd709d3"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Grec",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("b25017fe-4709-474d-9d28-73489c12730b"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Hongrois",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("b78239d4-c118-4887-8296-8494cef315bc"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Italien",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("e673effc-4ca5-46d4-bba8-0c4e5c658cb5"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Japonais",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("21a7b72e-456c-4b07-9cda-125917d43396"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Kikongo",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("25c764de-a813-4848-9d13-2ffea2a2ca44"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Kiswahili",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("09bf9503-dea6-4133-a3de-49d8cdcfcdc9"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Lingala",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("792a266d-f629-419a-8346-59400b460b2d"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Malgache",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("224a6eb6-c5c0-44a2-8504-46fa0f158527"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Malais",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("5ecd41d8-0a66-4315-b489-b26582e78e47"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Mongol",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("ac04b377-a830-43cc-b249-3ace079a4e61"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Néerlandais",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("bb490fb1-c45c-4735-ac44-3524dde36275"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Occitan",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("7dc19496-4d9b-413a-b088-090da9f29a08"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Ourdou",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("f2ed3127-4acd-4e4b-90b2-b51958dc1357"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Persan",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("39577e09-4464-41bc-b9ad-e69b03ba3266"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Portugais",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("0f6fda7c-e474-4196-8afb-1bab65bacfd1"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Quechua",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("05c38683-5c3a-43a9-a603-c553e429ab99"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Roumain",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("d63f7ab4-b41c-40f5-867b-03b2a7571aca"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Samoan",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("3b004521-dc2f-43ec-bd60-5e8c95aa9dae"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Serbe",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("cf3524e8-53a1-4170-81a0-191ebe2e9507"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Sesotho",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("9ed8dd18-affb-4a96-b35a-d0ed17943492"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Slovaque",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("3329384f-af76-4eb6-9f15-b8b838af7999"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Slovène",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("d4a4a33a-f5d3-488c-89ad-7f552d262b88"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Suédois",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("b809599c-6b49-452a-b26c-7438c059bbf8"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Tamoul",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("1aeef696-c31e-4987-84f3-2215a98bf350"),
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Turc",
                            Type = 1,
                            UtiCrea = "ALTEA"
                        });
                });

            modelBuilder.Entity("Altalents.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActif")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModifiable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupprimable")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MotDePasseCrypte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("Nom");

                    b.ToTable("Utilisateurs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f05d0f23-00b2-47fe-91ab-59ebeaa867ee"),
                            DateCrea = new DateTime(2021, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vlarguier@altea-si.com",
                            IsActif = true,
                            IsModifiable = false,
                            IsSupprimable = false,
                            Login = "admin",
                            MotDePasseCrypte = "AQAAAAIAAYagAAAAEJJ8k1QzsOQCivB/OZ4fO3oRItU9ubWJwyTeSVD8FisyZN0vG9+vG72E5MCF35op2w==",
                            Nom = "Super administrateur",
                            UtiCrea = "ALTEA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
