// <auto-generated />
using System;
using Altalents.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Altalents.DataAccess.Migrations
{
    [DbContext(typeof(MigrationContext))]
    [Migration("20240618142744_AddInfoDt")]
    partial class AddInfoDt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Altalents.Entities.Adresse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Adresse2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("PersonneId");

                    b.ToTable("Adresses", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<string>("Domaine")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Organisme")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PersonneId");

                    b.ToTable("Certifications", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("PersonneId");

                    b.HasIndex("TypeId");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PersonneId");

                    b.HasIndex("TypeId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.DocumentComplementaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commentaire")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<Guid>("DossierTechniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DossierTechniqueId");

                    b.ToTable("DocumentComplementaires", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.DossierTechnique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Commercial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<Guid>("DisponibiliteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Poste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PrixJour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("StatutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TokenAccesRapide")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DisponibiliteId");

                    b.HasIndex("PersonneId");

                    b.HasIndex("StatutId");

                    b.ToTable("DossierTechniques", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientFinal")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DomaineMetier")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Entreprise")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("IntitulePoste")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TypeContratId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PersonneId");

                    b.HasIndex("TypeContratId");

                    b.ToTable("Experiences", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<string>("Domaine")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Organisme")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PersonneId");

                    b.ToTable("Formations", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.LiaisonExperienceCompetance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompetanceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompetanceId");

                    b.HasIndex("ExperienceId");

                    b.ToTable("LiaisonExperienceCompetances", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.LiaisonExperienceTechnologie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Niveau")
                        .HasColumnType("int");

                    b.Property<Guid>("TechnologieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("TechnologieId");

                    b.ToTable("LiaisonExperienceTechnologies", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.Personne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BoondId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Trigramme")
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BoondId")
                        .IsUnique()
                        .HasFilter("[BoondId] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Trigramme")
                        .IsUnique()
                        .HasFilter("[Trigramme] IS NOT NULL");

                    b.HasIndex("TypeId");

                    b.ToTable("Personnes", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.PersonneLangue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<Guid>("LangueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<Guid>("PersonneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LangueId");

                    b.HasIndex("PersonneId");

                    b.ToTable("PersonneLangues", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.QuestionDossierTechnique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DossierTechniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Reponse")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DossierTechniqueId");

                    b.ToTable("QuestionDossierTechniques", (string)null);
                });

            modelBuilder.Entity("Altalents.Entities.Reference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("OrdreTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SousType")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "SousType");

                    b.ToTable("References", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc2fe62f-a81d-437b-a257-7e89b150042e"),
                            Code = "Anglais",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Anglais",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("2ad460a4-afa9-4ac0-986f-42d626b82bf1"),
                            Code = "Arabe",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Arabe",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("e47e9d1a-590d-4b4a-8f9e-219781d36902"),
                            Code = "Chinois",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Chinois",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("91cad6f6-cfb2-43bc-b5f5-a1e90ceba77c"),
                            Code = "Espagnol",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Espagnol",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("356fce26-caaa-4b4e-94d2-f7341d1851b1"),
                            Code = "Francais",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Français",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("3fbcdd3e-7dfa-46bb-bf5d-ae39e4137a07"),
                            Code = "Russe",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Russe",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("cfb960f2-d501-4154-a53a-83f9497bc0ad"),
                            Code = "Albanais",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Albanais",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("fe2be6bb-fbda-4115-bc06-5603447cbcbd"),
                            Code = "Allemand",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Allemand",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("9a5769e9-f63f-4f30-85d6-c785247a621a"),
                            Code = "Amazigh",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Amazigh",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("3ca6db24-303d-4fa3-9b5b-5cd8cfd02f11"),
                            Code = "Armenien",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Arménien",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("8883e43d-9d64-4976-a0de-cf2fce12c00d"),
                            Code = "Aymara",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Aymara",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("f3e4d4b8-4406-4098-ae7f-1ccbf938c5b8"),
                            Code = "Bengali",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Bengali",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("389314c5-b5b2-4055-85ef-a0a688b71d1c"),
                            Code = "Catalan",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Catalan",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("560f923c-27de-4891-8e96-db9fe47ca235"),
                            Code = "Coreen",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Coréen",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("077fa7cc-9f80-4d11-a791-1109ec17987b"),
                            Code = "Croate",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Croate",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("eb36539d-64bd-4cd7-adc9-27fe1c30a039"),
                            Code = "Danois",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Danois",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("41fb2299-36ec-4854-bc78-ee7899af318f"),
                            Code = "Ewe",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Éwé",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("57580b70-c631-4d9c-8dfa-920b54bfbfaf"),
                            Code = "Guarani",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Guarani",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("1fbfbf6e-957e-4565-afd1-173b5cd709d3"),
                            Code = "Grec",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Grec",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("b25017fe-4709-474d-9d28-73489c12730b"),
                            Code = "Hongrois",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Hongrois",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("b78239d4-c118-4887-8296-8494cef315bc"),
                            Code = "Italien",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Italien",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("e673effc-4ca5-46d4-bba8-0c4e5c658cb5"),
                            Code = "Japonais",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Japonais",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("21a7b72e-456c-4b07-9cda-125917d43396"),
                            Code = "Kikongo",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Kikongo",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("25c764de-a813-4848-9d13-2ffea2a2ca44"),
                            Code = "Kiswahili",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Kiswahili",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("09bf9503-dea6-4133-a3de-49d8cdcfcdc9"),
                            Code = "Lingala",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Lingala",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("792a266d-f629-419a-8346-59400b460b2d"),
                            Code = "Malgache",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Malgache",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("224a6eb6-c5c0-44a2-8504-46fa0f158527"),
                            Code = "Malais",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Malais",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("5ecd41d8-0a66-4315-b489-b26582e78e47"),
                            Code = "Mongol",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Mongol",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("ac04b377-a830-43cc-b249-3ace079a4e61"),
                            Code = "Neerlandais",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Néerlandais",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("bb490fb1-c45c-4735-ac44-3524dde36275"),
                            Code = "Occitan",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Occitan",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("7dc19496-4d9b-413a-b088-090da9f29a08"),
                            Code = "Ourdou",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Ourdou",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("f2ed3127-4acd-4e4b-90b2-b51958dc1357"),
                            Code = "Persan",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Persan",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("39577e09-4464-41bc-b9ad-e69b03ba3266"),
                            Code = "Portugais",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Portugais",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("0f6fda7c-e474-4196-8afb-1bab65bacfd1"),
                            Code = "Quechua",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Quechua",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("05c38683-5c3a-43a9-a603-c553e429ab99"),
                            Code = "Roumain",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Roumain",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("d63f7ab4-b41c-40f5-867b-03b2a7571aca"),
                            Code = "Samoan",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Samoan",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("3b004521-dc2f-43ec-bd60-5e8c95aa9dae"),
                            Code = "Serbe",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Serbe",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("cf3524e8-53a1-4170-81a0-191ebe2e9507"),
                            Code = "Sesotho",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Sesotho",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("9ed8dd18-affb-4a96-b35a-d0ed17943492"),
                            Code = "Slovaque",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Slovaque",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("3329384f-af76-4eb6-9f15-b8b838af7999"),
                            Code = "Slovene",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Slovène",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("d4a4a33a-f5d3-488c-89ad-7f552d262b88"),
                            Code = "Suedois",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Suédois",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("b809599c-6b49-452a-b26c-7438c059bbf8"),
                            Code = "Tamoul",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Tamoul",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("1aeef696-c31e-4987-84f3-2215a98bf350"),
                            Code = "Turc",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Turc",
                            OrdreTri = 0,
                            Type = "Langue",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("8f486cd6-6313-47f9-a4b5-5bd535c199a9"),
                            Code = "Immediate",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Immédiate",
                            OrdreTri = 1,
                            Type = "Disponibilite",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("92dfd90f-79b4-4d5e-93e6-fb7046b3416a"),
                            Code = "SousUnMois",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Sous un mois",
                            OrdreTri = 2,
                            Type = "Disponibilite",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("f35745ef-66d0-4cb0-9657-b57c2f149e3f"),
                            Code = "SousTroisMois",
                            DateCrea = new DateTime(2024, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Sous trois mois",
                            OrdreTri = 3,
                            Type = "Disponibilite",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("aad8f403-76c8-4dee-b9b5-8ed5a8a28eec"),
                            Code = "Telephone",
                            DateCrea = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Telephone",
                            OrdreTri = 1,
                            Type = "Contact",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("b3e98178-68dd-4de3-9e36-a2ed571f21c5"),
                            Code = "Cv",
                            DateCrea = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Cv",
                            OrdreTri = 1,
                            Type = "Document",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("3a325813-e79d-445a-8953-b665c7581901"),
                            Code = "Dt",
                            DateCrea = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Dt",
                            OrdreTri = 1,
                            Type = "Document",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("a60b074d-b4af-4157-ab49-453e28da8514"),
                            Code = "Cdi",
                            DateCrea = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "CDI",
                            OrdreTri = 1,
                            Type = "Contrat",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("4c573cda-fc0c-42fa-b571-7829f26149cc"),
                            Code = "Cdd",
                            DateCrea = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "CDD",
                            OrdreTri = 2,
                            Type = "Contrat",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("5f92b7d6-4ddf-4ec5-965b-9824387afa57"),
                            Code = "Cree",
                            DateCrea = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Créé",
                            OrdreTri = 1,
                            Type = "StatutDt",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("5f1d5f70-c35d-45c2-b0b8-6ee8ff2ea1a5"),
                            Code = "EnCours",
                            DateCrea = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "En Cours",
                            OrdreTri = 2,
                            Type = "StatutDt",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("610f6ca4-0f22-44ec-9269-f744873b92f2"),
                            Code = "NonValide",
                            DateCrea = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Non valide",
                            OrdreTri = 3,
                            Type = "StatutDt",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("78a3cb44-9fd3-4c6c-9848-677937324ecd"),
                            Code = "Valide",
                            DateCrea = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "Valide",
                            OrdreTri = 4,
                            Type = "StatutDt",
                            UtiCrea = "ALTEA"
                        },
                        new
                        {
                            Id = new Guid("02e3d3ee-f745-4bf1-a00d-61e640dac8ae"),
                            Code = "AModifier",
                            DateCrea = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Libelle = "A Modifier",
                            OrdreTri = 5,
                            Type = "StatutDt",
                            UtiCrea = "ALTEA"
                        });
                });

            modelBuilder.Entity("Altalents.Entities.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActif")
                        .HasColumnType("bit");

                    b.Property<bool>("IsModifiable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSupprimable")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MotDePasseCrypte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiCrea")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtiMaj")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("Nom");

                    b.ToTable("Utilisateurs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f05d0f23-00b2-47fe-91ab-59ebeaa867ee"),
                            DateCrea = new DateTime(2021, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vlarguier@altea-si.com",
                            IsActif = true,
                            IsModifiable = false,
                            IsSupprimable = false,
                            Login = "admin",
                            MotDePasseCrypte = "AQAAAAIAAYagAAAAEJJ8k1QzsOQCivB/OZ4fO3oRItU9ubWJwyTeSVD8FisyZN0vG9+vG72E5MCF35op2w==",
                            Nom = "Super administrateur",
                            UtiCrea = "ALTEA"
                        });
                });

            modelBuilder.Entity("Altalents.Entities.Adresse", b =>
                {
                    b.HasOne("Altalents.Entities.Personne", "Personne")
                        .WithMany("Adresses")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("Altalents.Entities.Certification", b =>
                {
                    b.HasOne("Altalents.Entities.Personne", "Personne")
                        .WithMany("Certifications")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("Altalents.Entities.Contact", b =>
                {
                    b.HasOne("Altalents.Entities.Personne", "Personne")
                        .WithMany("Contacts")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Altalents.Entities.Reference", "Type")
                        .WithMany("Contacts")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personne");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Altalents.Entities.Document", b =>
                {
                    b.HasOne("Altalents.Entities.Personne", "Personne")
                        .WithMany("Documents")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Altalents.Entities.Reference", "Type")
                        .WithMany("Documents")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personne");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Altalents.Entities.DocumentComplementaire", b =>
                {
                    b.HasOne("Altalents.Entities.DossierTechnique", "DossierTechnique")
                        .WithMany("DocumentComplementaires")
                        .HasForeignKey("DossierTechniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DossierTechnique");
                });

            modelBuilder.Entity("Altalents.Entities.DossierTechnique", b =>
                {
                    b.HasOne("Altalents.Entities.Reference", "Disponibilite")
                        .WithMany("DossierTechniquesByDisponibilite")
                        .HasForeignKey("DisponibiliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Altalents.Entities.Personne", "Personne")
                        .WithMany("DossierTechniques")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Altalents.Entities.Reference", "Statut")
                        .WithMany("DossierTechniquesByStatut")
                        .HasForeignKey("StatutId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Disponibilite");

                    b.Navigation("Personne");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("Altalents.Entities.Experience", b =>
                {
                    b.HasOne("Altalents.Entities.Personne", "Personne")
                        .WithMany("Experiences")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Altalents.Entities.Reference", "TypeContrat")
                        .WithMany("Experiences")
                        .HasForeignKey("TypeContratId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personne");

                    b.Navigation("TypeContrat");
                });

            modelBuilder.Entity("Altalents.Entities.Formation", b =>
                {
                    b.HasOne("Altalents.Entities.Personne", "Personne")
                        .WithMany("Formations")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("Altalents.Entities.LiaisonExperienceCompetance", b =>
                {
                    b.HasOne("Altalents.Entities.Reference", "Competance")
                        .WithMany("LiaisonExperienceCompetances")
                        .HasForeignKey("CompetanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Altalents.Entities.Experience", "Experience")
                        .WithMany("LiaisonExperienceCompetances")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Competance");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Altalents.Entities.LiaisonExperienceTechnologie", b =>
                {
                    b.HasOne("Altalents.Entities.Experience", "Experience")
                        .WithMany("LiaisonExperienceTechnologies")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Altalents.Entities.Reference", "Technologie")
                        .WithMany("LiaisonExperienceTechnologies")
                        .HasForeignKey("TechnologieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("Technologie");
                });

            modelBuilder.Entity("Altalents.Entities.Personne", b =>
                {
                    b.HasOne("Altalents.Entities.Reference", "Type")
                        .WithMany("Personnes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Altalents.Entities.PersonneLangue", b =>
                {
                    b.HasOne("Altalents.Entities.Reference", "Langue")
                        .WithMany("PersonneLangues")
                        .HasForeignKey("LangueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Altalents.Entities.Personne", "Personne")
                        .WithMany("PersonneLangues")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Langue");

                    b.Navigation("Personne");
                });

            modelBuilder.Entity("Altalents.Entities.QuestionDossierTechnique", b =>
                {
                    b.HasOne("Altalents.Entities.DossierTechnique", "DossierTechnique")
                        .WithMany("QuestionDossierTechniques")
                        .HasForeignKey("DossierTechniqueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DossierTechnique");
                });

            modelBuilder.Entity("Altalents.Entities.DossierTechnique", b =>
                {
                    b.Navigation("DocumentComplementaires");

                    b.Navigation("QuestionDossierTechniques");
                });

            modelBuilder.Entity("Altalents.Entities.Experience", b =>
                {
                    b.Navigation("LiaisonExperienceCompetances");

                    b.Navigation("LiaisonExperienceTechnologies");
                });

            modelBuilder.Entity("Altalents.Entities.Personne", b =>
                {
                    b.Navigation("Adresses");

                    b.Navigation("Certifications");

                    b.Navigation("Contacts");

                    b.Navigation("Documents");

                    b.Navigation("DossierTechniques");

                    b.Navigation("Experiences");

                    b.Navigation("Formations");

                    b.Navigation("PersonneLangues");
                });

            modelBuilder.Entity("Altalents.Entities.Reference", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Documents");

                    b.Navigation("DossierTechniquesByDisponibilite");

                    b.Navigation("DossierTechniquesByStatut");

                    b.Navigation("Experiences");

                    b.Navigation("LiaisonExperienceCompetances");

                    b.Navigation("LiaisonExperienceTechnologies");

                    b.Navigation("PersonneLangues");

                    b.Navigation("Personnes");
                });
#pragma warning restore 612, 618
        }
    }
}
