//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altalents.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibellesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibellesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Altalents.MVC.Resources.LibellesResources", typeof(LibellesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial.
        /// </summary>
        public static string Commercial {
            get {
                return ResourceManager.GetString("Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un DT.
        /// </summary>
        public static string CreerDT {
            get {
                return ResourceManager.GetString("CreerDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date création.
        /// </summary>
        public static string DateCreation {
            get {
                return ResourceManager.GetString("DateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière modification.
        /// </summary>
        public static string DateUpdate {
            get {
                return ResourceManager.GetString("DateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant Boond.
        /// </summary>
        public static string IdBoond {
            get {
                return ResourceManager.GetString("IdBoond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvaise combinaison Email/ mot de passe. Veuillez ressaisir vos informations de connexion ou contacter l’administrateur du site..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LoginIdentifiant {
            get {
                return ResourceManager.GetString("LoginIdentifiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string LoginMotDePasse {
            get {
                return ResourceManager.GetString("LoginMotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe est obligatoire..
        /// </summary>
        public static string LoginMotDePasseObligatoire {
            get {
                return ResourceManager.GetString("LoginMotDePasseObligatoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string MenuAccueil {
            get {
                return ResourceManager.GetString("MenuAccueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string MenuAdministration {
            get {
                return ResourceManager.GetString("MenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        public static string MenuDeconnexion {
            get {
                return ResourceManager.GetString("MenuDeconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du candidat.
        /// </summary>
        public static string NomCandidat {
            get {
                return ResourceManager.GetString("NomCandidat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num.
        /// </summary>
        public static string NumDT {
            get {
                return ResourceManager.GetString("NumDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poste.
        /// </summary>
        public static string Poste {
            get {
                return ResourceManager.GetString("Poste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poste souhaité.
        /// </summary>
        public static string PosteVoulu {
            get {
                return ResourceManager.GetString("PosteVoulu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prenom du candidat.
        /// </summary>
        public static string PrenomCandidat {
            get {
                return ResourceManager.GetString("PrenomCandidat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaire.
        /// </summary>
        public static string ReferenceCommentaireFun {
            get {
                return ResourceManager.GetString("ReferenceCommentaireFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libelle.
        /// </summary>
        public static string ReferenceLibelle {
            get {
                return ResourceManager.GetString("ReferenceLibelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Dt Associés.
        /// </summary>
        public static string ReferenceNbDtAssocie {
            get {
                return ResourceManager.GetString("ReferenceNbDtAssocie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ReferenceType {
            get {
                return ResourceManager.GetString("ReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string Statut {
            get {
                return ResourceManager.GetString("Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bibliothèque de DT.
        /// </summary>
        public static string TitreBiblioDT {
            get {
                return ResourceManager.GetString("TitreBiblioDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données à contrôler.
        /// </summary>
        public static string TitreDataControle {
            get {
                return ResourceManager.GetString("TitreDataControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des comptes d’utilisateur.
        /// </summary>
        public static string TitreGestionCompteUtilisateurs {
            get {
                return ResourceManager.GetString("TitreGestionCompteUtilisateurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion des DT.
        /// </summary>
        public static string TitreGestionDT {
            get {
                return ResourceManager.GetString("TitreGestionDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicateurs et Extractions.
        /// </summary>
        public static string TitreIndicateurExtract {
            get {
                return ResourceManager.GetString("TitreIndicateurExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de bord.
        /// </summary>
        public static string TitreTableauDeBord {
            get {
                return ResourceManager.GetString("TitreTableauDeBord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier un candidat.
        /// </summary>
        public static string TitreUpdateCandidat {
            get {
                return ResourceManager.GetString("TitreUpdateCandidat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner un type de mot-clé....
        /// </summary>
        public static string TypeReferenceComboBoxPlaceholder {
            get {
                return ResourceManager.GetString("TypeReferenceComboBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse e-mail.
        /// </summary>
        public static string UtilisateurEmail {
            get {
                return ResourceManager.GetString("UtilisateurEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiant.
        /// </summary>
        public static string UtilisateurLogin {
            get {
                return ResourceManager.GetString("UtilisateurLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string UtilisateurMotDePasse {
            get {
                return ResourceManager.GetString("UtilisateurMotDePasse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d’utilisateur.
        /// </summary>
        public static string UtilisateurNom {
            get {
                return ResourceManager.GetString("UtilisateurNom", resourceCulture);
            }
        }
    }
}
