name: .NET Build MVC angular using Shared Workflow

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    uses: altea-si-tech/ci-commons/.github/workflows/shared-ci.yml@main
    with:
      node-version: '20' # Version spécifique pour ce projet
      angular-cli-version: '16.2.16' # Optionnel, ou laisse 'latest'
      secret-npm: ${{ secrets.GITNPMPAT }} 
      path-cd: './ui/Altalents.MVC/Angular/Altalents-client'

    runs-on: windows-latest

    steps:

    - name: Build Angular project
      run: |
        cd ./ui/Altalents.MVC/Angular/Altalents-client
        ng build --configuration production;

    - name: Add NuGet source telerik
      run: dotnet nuget add source https://nuget.telerik.com/v3/index.json --name telerik --username ${{ secrets.TelerikLoginNuget }} --password ${{ secrets.TelerikPasswordNuget }}
    - name: Add NuGet source Github
      run: dotnet nuget add source https://nuget.pkg.github.com/AlteaTech/index.json --name AlteaTech --username AlteaTech --password ${{ secrets.GITHUBNUGET }}

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.0.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        
    - name: Restore NuGet Packages
      run: nuget restore Altalents.sln

    - name: Build
      run: msbuild Altalents.sln /p:Configuration=Debug /p:Platform="Any CPU"

    - name: dotnet publish
      if: github.event_name == 'push'
      run: |
        New-Item -Path ${{github.workspace}} -Name "altalentDeploy" -ItemType "directory"
        dotnet publish -c Debug -o ${{github.workspace}}/altalentDeploy

    - name: Upload artifact for deployment job
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{github.workspace}}/altalentDeploy

  deploy:
    runs-on: windows-latest 
    needs: build
    if: github.event_name == 'push'
    environment:
      name: 'Debug'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
          
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
